#!/bin/sh

KERNEL_DIR=/home/ethan/gits/out/riscv
ROOTFS=/home/ethan/gits/busybox/rootfs-riscv.cpio

qemu-system-riscv64 \
	-nographic -machine virt \
	-fsdev local,security_model=passthrough,id=fsdev0,path=share \
	-device virtio-9p-pci,fsdev=fsdev0,mount_tag=hostshare \
	-kernel $KERNEL_DIR/arch/riscv/boot/Image -append "rdinit=/linuxrc console=ttyS0" \
	-initrd $ROOTFS \
	-smp 4
