#!/bin/sh

KERNEL_DIR=/home/ethan/gits/out/linux/

qemu-system-aarch64 $@ \
	-fsdev local,security_model=passthrough,id=fsdev0,path=share \
	-device virtio-9p-pci,fsdev=fsdev0,mount_tag=hostshare \
	-machine virt,virtualization=true,gic-version=3,mte=on \
	-nographic \
	-m size=1024M \
	-cpu max \
	-smp 1 \
	-dtb qemu.dtb \
	-initrd ~/workspace/rootfs.cpio.gz \
	-kernel $KERNEL_DIR/arch/arm64/boot/Image \
	--append "console=ttyAMA0 rdinit=/linuxrc nokaslr"

#	-initrd rootfs.cpio.gz \
